### ISSUE TITLE
Connection Failure

### ISSUE THREAD

**Issue by ghost** [matsimitsu/iTrakt#2]
Hi,

I've download on the project ZIP (and SSkeychain zip too because it doesnt come in the package)

I launch the projet on my iPhone & i got this error on the device : A server with the specified hostname could not be found.

Why ?
Thanks.

**Comment by matsimitsu** [comment]
In lib/trakt.h the default url is specified:

```
#define BASE_URL @"http://itrakt.matsimitsu.com"
```

That was in a time where the trakt api didn't expose all the shows/episodes in a nice way. 
So we made a proxy that got the stuff we needed form the trakt api and mashed those requests together into a single json with all the required data.

With all the improvements trakt made you can now get everything straight from the trakt.tv api. So you'd probably have to rewrite some code in lib and the models to get it working.

**Comment by ghost** [comment]
Thanks for answer.
I'm not a developer so how can I do this ?
Is that possible to update the git project ? :D 

Thanks !
